# Introduction {#sec-intro}

Land cover is a physical characteristic of Earth's surface describing distribution of vegetation, water, soil and other features on the ground [@rawat_monitoring_2015].
The production of accurate land cover maps is crucial for conducting spatial analyses, studying environmental changes [@reis_analyzing_2008] and evaluating urban development [@hashem_change_2015].
Land cover information is also useful for the general circulation models (GCM) development [@running_ecosystem_2008] and has been selected as one of the most essential variables that contribute to describing Earth's environment and climate [@bojinski_concept_2014].

The main method of creating land cover maps is based on multispectral satellite data and remote-sensing methods.
The two most popular, free-of-charge sources of satellite imagery are Landsat programme (run by NASA and USGS) and Sentinel programme (conducted by ESA).
These datasets are usually utilized to create classification models based on machine learning techniques, which gained popularity in the recent years [@maxwell_implementation_2018].
A supervised machine learning model, including the one used in this study, analyzes training set containing labels of land cover classes and tries to learn how to recognize them.

Over the past few years, there were several attempts to automate creation of land cover maps [@malinowski_automated_2020; @witjes_spatiotemporal_2021].
An automated workflow, however, requires high understanding of every step of machine learning process and appropriate choice of explanatory variables.
Spectral bands and spectral indices are the most commonly used variables.
However, some satellites like Landsat 8, have a thermal sensor as well, which measures land surface temperature (LST) of the Earth.
There is a significant interaction between LST and extent of urban and impervious areas [@dutta_changing_2019], thus we can assume that this variable might be influential on the classification model results.
Thermal band's impact on the model results is described in several studies, for example, @rodriguez-galiano_incorporating_2012, @zhao_exploring_2019, @sun_improvement_2015.
However, despite adding completely new information compared to spectral bands, the thermal band is noticeably more often omitted in classification models, probably due to its coarser resolution [@rodriguez-galiano_incorporating_2012].
Because of this, its impact on model predictions is not clear enough and needs further research.

The main goal of this study is to evaluate thermal band's impact on a classification model, study its spatial distribution and try to give broader knowledge of how it should be used.
Random Forest model will be trained on a dataset for Poland and a land cover map of Poznań metropolitan area will be created.
Then, both the machine learning model and the result map will be used to measure thermal band's impact on the classification results.
