# Assessing model quality {#sec-results-eval}

Table with quality indices:

-   overall accuracy (OA) / classification error (CE)

-   producer's and user's accuracy (PA, UA) / recall and precision

-   F1-score

-   Kappa coefficient

```{r tabela3, echo=FALSE}
#| label: tbl-tabela4
#| echo: false
#| tbl-cap: "Measures of overall model accuracy calculated during cross-validation/resampling process."
df = data.frame(
  measure = c("overall accuracy", "Kappa coefficient", "precission (UA)", "recall (PA)", "F1-score"),
  average_value = c(0.75, 0.70, 0.8, 0.78, 0.79)
)
colnames(df) = c("Measure", "Avg. value")
df |>
  knitr::kable(format = "latex", booktabs = TRUE, linesep = "") |> 
  kableExtra::row_spec(0, bold = TRUE, extra_css = "border-left: 1px solid grey; border-right: 1px solid grey") |>
  kableExtra::column_spec(1, border_left = TRUE) |>
  kableExtra::column_spec(2, border_left = TRUE, border_right = TRUE) |>
  kableExtra::kable_classic(full_width = FALSE) |>
  kableExtra::row_spec(1:(nrow(df) - 1), extra_latex_after = "\\hline")
```

```{r tabela3, echo=FALSE}
#| label: tbl-tabela5
#| echo: false
#| tbl-cap: "Accuracy measures by land cover class."
df = data.frame(
  class = c("arable land", "grasslands", "forests", "bare land", "artificial land", "water bodies", "wetlands"),
  precision = c(0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8),
  recall = c(0.75, 0.70, 0.8, 0.78, 0.79, 0.8, 0.8),
  f1score = c(0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8)
)
colnames(df) = c("Land cover class", "Recall (producer's accuracy)", "Precision (user's accuracy)", "F1-score")
df |>
  knitr::kable(format = "latex", booktabs = TRUE, linesep = "") |> 
  kableExtra::row_spec(0, bold = TRUE, extra_css = "border-left: 1px solid grey; border-right: 1px solid grey") |>
  kableExtra::column_spec(1:3, border_left = TRUE) |>
  kableExtra::column_spec(4, border_left = TRUE, border_right = TRUE) |>
  kableExtra::kable_classic(full_width = FALSE) |>
  kableExtra::row_spec(1:(nrow(df) - 1), extra_latex_after = "\\hline")
```
