project:
  type: book
  output-dir: docs

title: "Ocena wpływu zastosowania kanału termalnego Landsat na wyniki nadzorowanej klasyfikacji pokrycia terenu"
titleeng: "Measuring impact of adding Landsat 8 thermal band on supervised land cover classification"
degreetype: "Praca inżynierska"
author: "Tomasz Matuszek"
major: "Geoinformacja"
albumid: "000000"
year: "2022"

book:
  output-file: "tomaszmatuszek"
  number-sections: true
  chapters:
    - index.qmd
    #- 00-oswiadczenie.qmd
    #- 00-abstrakt.qmd
    - 01-roz1.qmd
    - 02-roz2.qmd
    - 03-roz3.qmd
    - 04-roz4.qmd
    - 05-roz5.qmd
    - 06-roz6.qmd

bibliography:
  - papers.bib

format:
  pdf:
    template: amuthesis.tex
    keep-tex: true
    pdf-engine: pdflatex
    cite-method: biblatex
    fig-height: 3.8
    fig-width: 6.3
    fig-asp: 0.618  # 1 / phi
    fig-pos: 't'
