project:
  type: book
  output-dir: docs

title: "Measuring an impact of the Landsat 8 thermal band on the supervised land cover classification results"
titleeng: "Ocena wpływu zastosowania kanału termalnego Landsat na wyniki nadzorowanej klasyfikacji pokrycia terenu"
degreetype: "Engineer's thesis"
author: "Tomasz Matuszek"
major: "Geoinformation"
albumid: "455828"
year: "2023"

book:
  output-file: "tomaszmatuszek"
  number-sections: true
  chapters:
    - index.qmd
    - 01-roz1.qmd
    - 02-roz2.qmd
    - 03-roz3.qmd
    - 04-roz4.qmd
    - 05-roz5.qmd
    - 06-roz6.qmd
    - 07-roz7.qmd

bibliography:
  - thesis.bib
  - packages.bib

format:
  pdf:
    template: amuthesis.tex
    keep-tex: true
    pdf-engine: pdflatex
    cite-method: biblatex
    fig-height: 3.8
    fig-width: 6.3
    fig-asp: 0.618  # 1 / phi
    fig-pos: 't'
